# -*- coding: utf-8 -*-
"""MINI LLM FROM SCRATCH.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13xG9h8c0N1VR7GDa6XLzZXwRWjdr8-ls
"""

import torch
import torch.nn as nn
from datasets import load_dataset

dataset = load_dataset("wikitext", "wikitext-2-raw-v1")
text = " ".join(dataset["train"]["text"][:1000])  # small subset for speed

chars = sorted(list(set(text)))
vocab_size = len(chars)

stoi = {ch: i for i, ch in enumerate(chars)}
itos = {i: ch for ch, i in stoi.items()}

def encode(s):
    return [stoi[c] for c in s]

def decode(l):
    return "".join([itos[i] for i in l])

data = torch.tensor(encode(text), dtype=torch.long)

n = int(0.9 * len(data))
train_data = data[:n]
val_data = data[n:]

batch_size = 32
block_size = 64
max_iters = 5000
lr = 3e-4
device = "cuda" if torch.cuda.is_available() else "cpu"

def get_batch(split):
    data = train_data if split == "train" else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))

    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])

    return x.to(device), y.to(device)

class BigramLanguageModel(nn.Module):
    def __init__(self, vocab_size):
        super().__init__()
        self.token_embedding = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):
        logits = self.token_embedding(idx)

        if targets is None:
            return logits, None

        B, T, C = logits.shape
        logits = logits.view(B*T, C)
        targets = targets.view(B*T)

        loss = nn.functional.cross_entropy(logits, targets)
        return logits, loss

    def generate(self, idx, max_new_tokens, temperature=0.8):
        for _ in range(max_new_tokens):
            logits, _ = self(idx)
            logits = logits[:, -1, :] / temperature
            probs = torch.softmax(logits, dim=-1)

            next_idx = torch.argmax(probs, dim=-1, keepdim=True)
            idx = torch.cat((idx, next_idx), dim=1)

        return idx

model = BigramLanguageModel(vocab_size).to(device)
optimizer = torch.optim.AdamW(model.parameters(), lr=lr)

for iter in range(max_iters):
    xb, yb = get_batch("train")

    logits, loss = model(xb, yb)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if iter % 500 == 0:
        print(f"Step {iter}, Loss: {loss.item():.4f}")

start = torch.zeros((1,1), dtype=torch.long).to(device)
generated = model.generate(start, max_new_tokens=200)

print("\nGenerated Text:\n")
print(decode(generated[0].tolist()))

